StudentWebApp/Controllers/ViewCoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentWebApp.Controllers
{
    public class ViewCoursesController : Controller
    {
        // GET: Program
        public ActionResult Art()
        {
            return View();
        }
        public ActionResult Music()
        {
            return View();
        }
        public ActionResult Reading()
        {
            return View();
        }
        public ActionResult Outdoor()
        {
            return View();
        }
    }
}

StudentWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @*@Scripts.Render("~/Content/datatablescss")*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ABC Kindergarten", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("Programs", "Index", "Program")</li>*@
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">ViewCourses <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Art Work", "Art", "ViewCourses")</li>
                            <li>@Html.ActionLink("Outdoor Activities", "Outdoor", "ViewCourses")</li>
                            <li>@Html.ActionLink("Music", "Music", "ViewCourses")</li>
                            <li>@Html.ActionLink("Reading", "Reading", "ViewCourses")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Teachers", "Index", "Teachers")</li>
                    <li>@Html.ActionLink("Schedule", "Index", "Schedule")</li>
                    <li>@Html.ActionLink("About Us", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                    @{
                        if (User.Identity.IsAuthenticated && Roles.GetRolesForUser().Length > 0)
                        {
                            <li>@Html.ActionLink("Students", "Index", "Students")</li>
                            <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                            @*<li>Welcome @User.Identity.Name  |  @Roles.GetRolesForUser()[0]</li>*@
                            <li>  Welcome @User.Identity.Name   </li>

                        }
                        else
                        {
                            <li> @Html.ActionLink("Login", "Login", "Account") </li>
                            <li> @Html.ActionLink("Register", "Register", "Account") </li>
                        }
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>
</body>
</html>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/datatablesjs")
@RenderSection("scripts", required: false)